name: Auto Update Subscribe Resource

on:
  schedule:
    - cron: '* */1 * * *'  #UTC0 每间隔一小时执行一次
  workflow_dispatch:       # 支持手动触发

permissions:
  contents: write  # 允许写入仓库内容

jobs:
  update-wiki-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出主仓库（包含 v2_sub, ssr_sub 和 脚本）
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 3. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 4. 安装 Python 依赖
      - name: Install Dependencies
        run: |
          pip install requests

      # 5. 运行更新脚本
      - name: Run Update Script
        run: |
          python update_sub_by_md.py

      # 6. 提交和推送更新到主仓库
      - name: Commit and Push Updates
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"          
          git add .
          git commit -m "Auto-update subscribe file" || echo "No changes to commit"          
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/HikerX/zhifan_subscribe.git
